name: Laravel CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: pdo, sqlite, pdo_sqlite, mbstring, xml, ctype, iconv, intl, pdo_mysql
          coverage: xdebug

      - name: Copy environment file
        run: cp .env.example .env

      - name: Configure environment for testing
        run: |
          echo "APP_ENV=testing" >> .env
          echo "DB_CONNECTION=sqlite" >> .env
          echo "DB_DATABASE=/home/runner/work/AQI/AQI/database/database.sqlite" >> .env

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Generate application key
        run: php artisan key:generate

      - name: Create SQLite database
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Run database migrations
        run: php artisan migrate --force

      - name: Generate timestamp
        run: echo "TIMESTAMP=$(date +%Y%m%d_%H%M%S)" >> $GITHUB_ENV

      - name: Run PHP tests with coverage
        run: |
          mkdir -p reports
          TIMESTAMP=$(date +%Y%m%d_%H%M%S)
          ./vendor/bin/phpunit --coverage-html=reports/coverage_${TIMESTAMP} --coverage-clover=reports/coverage_${TIMESTAMP}/coverage.xml
          echo "REPORT_DIR=coverage_${TIMESTAMP}" >> $GITHUB_ENV

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: php-coverage-report-${{ env.TIMESTAMP }}
          path: reports/${{ env.REPORT_DIR }}
